In [3]:
from google.colab import files
uploaded=files.upload()

Saving lab1_datasets.xlsx to lab1_datasets.xlsx

In [4]:
import pandas as pd
data='lab1_datasets.xlsx'
df=pd.read_excel(data)
df

,Customer,Candies (#),Mangoes (Kg),Milk Packets (#),Payment (Rs),Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Candy,Mango,Milk
0,C_1,20,6,2,386,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,55.0,18.0
1,C_2,16,3,6,289,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,C_3,27,6,2,393,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,C_4,19,1,2,110,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,C_5,24,4,2,280,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,C_6,22,1,5,167,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,C_7,15,4,2,271,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,C_8,18,4,2,274,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,C_9,21,1,4,148,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,C_10,16,2,4,198,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.drop(df.iloc[:,5:18],inplace=True,axis=1)
df

,Customer,Candies (#),Mangoes (Kg),Milk Packets (#),Payment (Rs),Unnamed: 18,Candy,Mango,Milk
0,C_1,20,6,2,386,NaN,1.0,55.0,18.0
1,C_2,16,3,6,289,NaN,NaN,NaN,NaN
2,C_3,27,6,2,393,NaN,NaN,NaN,NaN
3,C_4,19,1,2,110,NaN,NaN,NaN,NaN
4,C_5,24,4,2,280,NaN,NaN,NaN,NaN
5,C_6,22,1,5,167,NaN,NaN,NaN,NaN
6,C_7,15,4,2,271,NaN,NaN,NaN,NaN
7,C_8,18,4,2,274,NaN,NaN,NaN,NaN
8,C_9,21,1,4,148,NaN,NaN,NaN,NaN
9,C_10,16,2,4,198,NaN,NaN,NaN,NaN

In [6]:
df = df.drop(['Unnamed: 18'],axis = 1)

In [7]:
df

,Customer,Candies (#),Mangoes (Kg),Milk Packets (#),Payment (Rs),Candy,Mango,Milk
0,C_1,20,6,2,386,1.0,55.0,18.0
1,C_2,16,3,6,289,NaN,NaN,NaN
2,C_3,27,6,2,393,NaN,NaN,NaN
3,C_4,19,1,2,110,NaN,NaN,NaN
4,C_5,24,4,2,280,NaN,NaN,NaN
5,C_6,22,1,5,167,NaN,NaN,NaN
6,C_7,15,4,2,271,NaN,NaN,NaN
7,C_8,18,4,2,274,NaN,NaN,NaN
8,C_9,21,1,4,148,NaN,NaN,NaN
9,C_10,16,2,4,198,NaN,NaN,NaN

In [8]:
df=df.drop(['Candy','Mango',	'Milk'],axis=1)

In [9]:
df

  Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)
0      C_1           20             6                 2           386
1      C_2           16             3                 6           289
2      C_3           27             6                 2           393
3      C_4           19             1                 2           110
4      C_5           24             4                 2           280
5      C_6           22             1                 5           167
6      C_7           15             4                 2           271
7      C_8           18             4                 2           274
8      C_9           21             1                 4           148
9     C_10           16             2                 4           198

In [10]:
a=df.iloc[:,1:4].values

In [11]:
a

array([[20,  6,  2],
       [16,  3,  6],
       [27,  6,  2],
       [19,  1,  2],
       [24,  4,  2],
       [22,  1,  5],
       [15,  4,  2],
       [18,  4,  2],
       [21,  1,  4],
       [16,  2,  4]])

In [24]:
b=df.iloc[:,4].values

In [25]:
b

array([386, 289, 393, 110, 280, 167, 271, 274, 148, 198])

In [15]:
import numpy as np
rank = np.linalg.matrix_rank(a)
print(rank)

3

In [32]:
c = np.linalg.pinv(a)
print(psuedo)

[[-0.01008596 -0.03124505  0.01013951  0.0290728   0.0182907   0.01161794
  -0.00771348  0.00095458  0.01743623 -0.00542016]
 [ 0.09059668  0.07263726  0.03172933 -0.09071908 -0.01893196 -0.06926996
   0.05675464  0.03152577 -0.07641966  0.00357352]
 [ 0.00299878  0.15874243 -0.05795468 -0.06609024 -0.06295043  0.03348017
   0.01541831 -0.01070461  0.00029003  0.05938755]]

In [22]:
dimension = a.shape
print(dimension)

(10, 3)

In [23]:
vectors = a.shape[0]
print(vectors)

10

In [34]:
costs = np.dot(psuedo, b)
print(costs)

[ 1. 55. 18.]

In [36]:
cost = np.dot(psuedo, b)
print(cost)

[ 1. 55. 18.]

In [41]:
df['Label'] = np.where(df['Payment (Rs)'] > 200, 'Rich', 'Poor')

In [42]:
df

  Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs) Label
0      C_1           20             6                 2           386  Rich
1      C_2           16             3                 6           289  Rich
2      C_3           27             6                 2           393  Rich
3      C_4           19             1                 2           110  Poor
4      C_5           24             4                 2           280  Rich
5      C_6           22             1                 5           167  Poor
6      C_7           15             4                 2           271  Rich
7      C_8           18             4                 2           274  Rich
8      C_9           21             1                 4           148  Poor
9     C_10           16             2                 4           198  Poor

In [43]:
x = df.iloc[:,1:5].values
x

array([[ 20,   6,   2, 386],
       [ 16,   3,   6, 289],
       [ 27,   6,   2, 393],
       [ 19,   1,   2, 110],
       [ 24,   4,   2, 280],
       [ 22,   1,   5, 167],
       [ 15,   4,   2, 271],
       [ 18,   4,   2, 274],
       [ 21,   1,   4, 148],
       [ 16,   2,   4, 198]])

In [44]:
y = df.iloc[:,5].values
y

array(['Rich', 'Rich', 'Rich', 'Poor', 'Rich', 'Poor', 'Rich', 'Rich',
       'Poor', 'Poor'], dtype=object)

In [46]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [47]:
classifier = LogisticRegression()

In [48]:
classifier.fit(X_train, y_train)

LogisticRegression()

In [51]:
y_pred = classifier.predict([[20,2,10,190]])
y_pred

array(['Poor'], dtype=object)